CREATE FUNCTION dabarc.fnt_get_formtatime (@STR_SEC NCHAR(20))
RETURNS NCHAR(20)
AS 
BEGIN

		DECLARE @NTIME	INT

		DECLARE @N_HOURS	INT
		DECLARE @N_MINUTE	INT
		DECLARE @N_SECOND	INT
		DECLARE @N_MOND		INT

		SET @NTIME = CAST(@STR_SEC AS INT)
		SET @N_HOURS = @NTIME/3600
		SET @N_MOND  = @NTIME % 3600

		SET @N_MINUTE = @N_MOND / 60
		SET @N_SECOND = @N_MOND % 60

		RETURN RTRIM(CAST(@N_HOURS AS CHAR(2))) + 'h:' + RTRIM(CAST(@N_MINUTE AS CHAR(2))) + 'm:' +  RTRIM(CAST(@N_SECOND AS CHAR(2))) + 's'
END
