
CREATE FUNCTION [dbo].[EXTRACT_NUM](@MSJ AS VARCHAR(max))
RETURNS INT
AS
BEGIN
 
WHILE PATINDEX('%[^0-9]%', @MSJ) > 0
 BEGIN
  SET @MSJ = REPLACE(@MSJ,SUBSTRING(@MSJ,PATINDEX('%[^0-9]%', @MSJ),1),'')
 END
 
 RETURN LEFT(@MSJ, 10)
END
