CREATE TABLE [dabarc].[Hoja_ConversionDeTipos] (
    [ConnectionType]         NVARCHAR (255) NULL,
    [ProcessOrder]           FLOAT (53)     NULL,
    [DataValidateControl]    NVARCHAR (255) NULL,
    [DataType]               NVARCHAR (255) NULL,
    [DataLength]             FLOAT (53)     NULL,
    [DataPrecision]          FLOAT (53)     NULL,
    [DataScale]              FLOAT (53)     NULL,
    [ProcessFlag]            NVARCHAR (255) NULL,
    [NewDataTypeFormat]      NVARCHAR (255) NULL,
    [NewDataType]            NVARCHAR (255) NULL,
    [NewDataLength]          NVARCHAR (255) NULL,
    [NewDataPrecision]       FLOAT (53)     NULL,
    [NewDataScale]           FLOAT (53)     NULL,
    [ColumnOverrideTemplate] NVARCHAR (255) NULL,
    [DeltaDataType]          NVARCHAR (255) NULL,
    [AddedBy]                NVARCHAR (255) NULL,
    [AddedOn]                NVARCHAR (255) NULL,
    [ChangedBy]              NVARCHAR (255) NULL,
    [ChangedOn]              NVARCHAR (255) NULL,
    [boaStatus]              NVARCHAR (255) NULL,
    [AddedVia]               NVARCHAR (255) NULL,
    [ChangedVia]             NVARCHAR (255) NULL
);

