CREATE TABLE [dabarc].[t_ODBC] (
    [odbc_id]            INT            IDENTITY (1, 1) NOT NULL,
    [driver_id]          INT            NOT NULL,
    [odbc_name]          NVARCHAR (60)  NOT NULL,
    [odbc_server]        NVARCHAR (60)  NOT NULL,
    [odbc_database]      NVARCHAR (30)  NOT NULL,
    [odbc_esquema]       NVARCHAR (30)  NOT NULL,
    [odbc_user]          NVARCHAR (30)  NOT NULL,
    [odbc_pasword]       NVARCHAR (30)  NOT NULL,
    [create_date]        DATETIME       NULL,
    [register_user]      NVARCHAR (15)  NULL,
    [modify_date]        DATETIME       NULL,
    [modify_user]        NVARCHAR (15)  NULL,
    [last_error]         NVARCHAR (256) NULL,
    [status]             INT            NULL,
    [file_path]          NVARCHAR (500) NULL,
    [file_separation]    NCHAR (5)      NULL,
    [odbc_type]          NCHAR (10)     NULL,
    [odbc_port]          NVARCHAR (5)   NULL,
    [odbc_protocol]      NVARCHAR (20)  NULL,
    [odbc_infoServidor]  NVARCHAR (60)  NULL,
    [odbc_infoServicio]  NVARCHAR (30)  NULL,
    [odbc_infoProtocolo] NVARCHAR (30)  NULL,
    [odbc_notcolname]    BIT            CONSTRAINT [DF_t_ODBC_odbc_notcolname] DEFAULT ((0)) NULL,
    [file_dll]           NVARCHAR (500) NULL,
    [odbc_alias]         NVARCHAR (60)  NULL,
    CONSTRAINT [PK_t_ODBC] PRIMARY KEY CLUSTERED ([odbc_id] ASC)
);

