CREATE TABLE [dabarc].[t_recording_script] (
    [script_id]           INT            IDENTITY (1, 1) NOT NULL,
    [team_id]             INT            NULL,
    [script_activo]       BIT            NOT NULL,
    [script_name]         NVARCHAR (100) NULL,
    [script_description]  NVARCHAR (500) NULL,
    [script_priority]     INT            NOT NULL,
    [script_transcode]    NVARCHAR (50)  NOT NULL,
    [script_structure]    NVARCHAR (10)  NOT NULL,
    [script_sourceviewh]  NVARCHAR (100) NULL,
    [script_sourcefieldh] NVARCHAR (50)  NULL,
    [script_sourcefieldd] NVARCHAR (50)  NULL,
    [script_noscreens]    INT            NOT NULL,
    [usuario_alta]        NVARCHAR (100) NULL,
    [fecha_alta]          DATETIME       NULL,
    [usuario_modifica]    NVARCHAR (100) NULL,
    [fecha_modifica]      DATETIME       NULL,
    [script_nofields]     INT            NULL,
    [execute_date]        DATETIME       NULL,
    [execute_user]        NVARCHAR (100) NULL,
    [execute_time]        NVARCHAR (25)  NULL,
    [affected_rows]       INT            NULL,
    [script_typeamount]   NCHAR (10)     NULL,
    [script_fileamount]   INT            NULL,
    [script_toptrans]     INT            NULL,
    [last_error]          NVARCHAR (256) NULL,
    [status]              INT            NULL,
    CONSTRAINT [PK_t_team_script] PRIMARY KEY CLUSTERED ([script_id] ASC)
);

