CREATE TABLE [dabarc].[t_RFM] (
    [rule_id]           INT            IDENTITY (1, 1) NOT NULL,
    [name]              NVARCHAR (128) NOT NULL,
    [description]       NVARCHAR (256) NULL,
    [short_description] NVARCHAR (50)  NULL,
    [active]            BIT            CONSTRAINT [DF_t_RFM_active] DEFAULT ((0)) NOT NULL,
    [priority]          INT            CONSTRAINT [DF_t_RFM_priority] DEFAULT ((0)) NOT NULL,
    [create_date]       DATETIME       NOT NULL,
    [register_date]     DATETIME       NULL,
    [execute_date]      DATETIME       NULL,
    [register_user]     NVARCHAR (15)  NULL,
    [execute_user]      NVARCHAR (15)  NULL,
    [execute_time]      NVARCHAR (25)  NULL,
    [affected_rows]     INT            CONSTRAINT [DF_t_RFM_affected_rows] DEFAULT ((0)) NOT NULL,
    [modify_date]       DATETIME       NULL,
    [modify_user]       NVARCHAR (15)  NULL,
    [registered]        BIT            CONSTRAINT [DF_t_RFM_registered] DEFAULT ((0)) NOT NULL,
    [table_id]          INT            NULL,
    [status]            INT            CONSTRAINT [DF_t_RFM_status] DEFAULT ((0)) NULL,
    [last_error]        NVARCHAR (256) CONSTRAINT [DF_t_RFM_last_error] DEFAULT (N'Sin ejecutar') NULL,
    [report_type]       CHAR (14)      NULL,
    CONSTRAINT [PK_t_RFM] PRIMARY KEY CLUSTERED ([rule_id] ASC),
    CONSTRAINT [FK_t_RFM_t_TFM] FOREIGN KEY ([table_id]) REFERENCES [dabarc].[t_TFM] ([table_id]) ON UPDATE CASCADE
);

