CREATE TABLE [dabarc].[t_SSIS] (
    [ssis_id]           INT             IDENTITY (1, 1) NOT NULL,
    [name]              NVARCHAR (128)  NOT NULL,
    [description]       NVARCHAR (256)  NULL,
    [short_description] NVARCHAR (50)   NULL,
    [active]            BIT             CONSTRAINT [DF_t_SSIS_active] DEFAULT ((0)) NOT NULL,
    [priority]          INT             CONSTRAINT [DF_t_SSIS_priority] DEFAULT ((0)) NOT NULL,
    [create_date]       DATETIME        NOT NULL,
    [register_date]     DATETIME        NULL,
    [execute_date]      DATETIME        NULL,
    [register_user]     NVARCHAR (15)   NULL,
    [execute_user]      NVARCHAR (15)   NULL,
    [execute_time]      NVARCHAR (25)   NULL,
    [affected_rows]     INT             CONSTRAINT [DF_t_SSIS_affected_rows] DEFAULT ((0)) NOT NULL,
    [modify_date]       DATETIME        NULL,
    [modify_user]       NVARCHAR (15)   NULL,
    [registered]        BIT             CONSTRAINT [DF_t_SSIS_registered] DEFAULT ((0)) NOT NULL,
    [last_error]        NVARCHAR (256)  NULL,
    [status]            INT             NULL,
    [table_id]          INT             NULL,
    [path]              NVARCHAR (1000) NULL,
    [database_id]       INT             NULL,
    CONSTRAINT [PK_t_SSIS] PRIMARY KEY CLUSTERED ([ssis_id] ASC)
);

